/**
 * Music Track Catalog for Peculiar Beats (Sonic Vanguard)
 * Hosted on Cloudflare R2:
 * - Preview clips (45s gating before purchase)
 * - Full Uncut Master Audio (streamable & downloadable after purchase)
 */

export const R2_BASE = "https://pub-f1a3f69c340e4dec8fda3b8eb74ce3ce.r2.dev";

export const musicTracks = [
  {
    id: "neon-pulse",
    title: "Neon Pulse",
    subtitle: "Festival Peak Time Mix",
    artist: "Peculiar Beats",
    genre: "Peak Time Techno",
    bpm: 130,
    key: "Fm",
    duration: "4:12",
    durationSec: 252,
    releaseDate: "2026-02-14",
    price: "$4.99",
    priceInr: "₹399",
    coverArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    previewUrl: `${R2_BASE}/previews/soundhelix_preview.mp3`,
    fullAudioUrl: `${R2_BASE}/artwork/SoundHelix.mp3`,
    downloadUrl: `${R2_BASE}/artwork/SoundHelix.mp3`,
    paymentUrl: "https://rzp.io/l/neonpulse",
    tags: ["Festival Ready", "Heavy Bass", "24-bit WAV Included"],
    description: "Driving underground techno with hypnotic modular synth leads, massive sub pressure, and an electrifying drop built for stadium sound systems.",
    isExclusive: true,
    isPopular: true,
  },
  {
    id: "delhi-after-dark",
    title: "Delhi After Dark",
    subtitle: "Club Edit & Extended Intro",
    artist: "Peculiar Beats",
    genre: "Afro & Tech House",
    bpm: 126,
    key: "Am",
    duration: "5:08",
    durationSec: 308,
    releaseDate: "2026-02-01",
    price: "$4.99",
    priceInr: "₹399",
    coverArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    fullAudioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    paymentUrl: "https://rzp.io/l/delhiafterdark",
    tags: ["Afro Tech", "Groovy Percussion", "Club Favorite"],
    description: "Deep tribal grooves fused with rolling tech-house basslines and atmospheric late-night textures, tested in club sets across 20+ cities.",
    isExclusive: false,
    isPopular: true,
  },
  {
    id: "cyber-odyssey",
    title: "Cyber Odyssey",
    subtitle: "Original Club Mix",
    artist: "Peculiar Beats",
    genre: "Melodic Techno",
    bpm: 128,
    key: "G#m",
    duration: "4:45",
    durationSec: 285,
    releaseDate: "2026-01-20",
    price: "$5.99",
    priceInr: "₹449",
    coverArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    fullAudioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    paymentUrl: "https://rzp.io/l/cyberodyssey",
    tags: ["Melodic", "Euphoric Lead", "Mastered for Big Systems"],
    description: "An emotional, futuristic journey featuring lush analog arp sequences, towering builds, and an uplifting breakdown that ignites sunset sessions.",
    isExclusive: true,
    isPopular: false,
  },
  {
    id: "sub-zero-bass",
    title: "Sub Zero Bass",
    subtitle: "VIP Dubplate",
    artist: "Peculiar Beats",
    genre: "Bass & UK Garage",
    bpm: 134,
    key: "Dm",
    duration: "3:54",
    durationSec: 234,
    releaseDate: "2026-01-08",
    price: "$4.99",
    priceInr: "₹399",
    coverArt: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    fullAudioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    paymentUrl: "https://rzp.io/l/subzerobass",
    tags: ["UK Garage", "Heavy Wobble", "Dubplate"],
    description: "Raw syncopated percussion, 2-step swing, and speaker-rattling sub frequency designed for bass lovers and underground warehouse raves.",
    isExclusive: false,
    isPopular: false,
  },
  {
    id: "bollywood-frequencies",
    title: "Bollywood Frequencies",
    subtitle: "Festival Mashup / Re-Drum",
    artist: "Peculiar Beats",
    genre: "Bollywood Fusion",
    bpm: 128,
    key: "Cm",
    duration: "4:30",
    durationSec: 270,
    releaseDate: "2025-12-28",
    price: "$3.99",
    priceInr: "₹299",
    coverArt: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    fullAudioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    paymentUrl: "https://rzp.io/l/bollywoodfrequencies",
    tags: ["Crowd Pleaser", "Wedding & Club Anthem", "High Energy"],
    description: "High-octane commercial fusion blending iconic desi hooks with modern punchy electronic basslines. A proven crowd pleaser across 600+ gigs.",
    isExclusive: true,
    isPopular: true,
  },
  {
    id: "aurora-drift",
    title: "Aurora Drift",
    subtitle: "Sunset Chillout Mix",
    artist: "Peculiar Beats",
    genre: "Deep Progressive",
    bpm: 122,
    key: "Em",
    duration: "5:22",
    durationSec: 322,
    releaseDate: "2025-12-15",
    price: "$4.99",
    priceInr: "₹399",
    coverArt: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    fullAudioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    paymentUrl: "https://rzp.io/l/auroradrift",
    tags: ["Sunset Vibes", "Lush Atmosphere", "Organic Textures"],
    description: "Hypnotic pads, organic world percussion, and a warm bassline that captures the golden hour vibe for lounge and beachside festival stages.",
    isExclusive: false,
    isPopular: false,
  }
];

export const trackGenres = [
  "All Tracks",
  "Peak Time Techno",
  "Afro & Tech House",
  "Melodic Techno",
  "Bass & UK Garage",
  "Bollywood Fusion",
  "Deep Progressive",
];
